import { useEffect, useState } from 'preact/hooks';
import { FALLBACK_BLOCK_HEIGHT } from '@/lib/block-height';

const GENESIS_TS = 1231006505000;
const HALVING_INTERVAL = 210000;
const MAX_SUPPLY = 21_000_000;

interface PulseSnapshot {
  height?: number;
  hashRate?: number | null;
  mempoolCount?: number | null;
  nodeCount?: number | null;
}

function spellNumber(n: number): string {
  if (n === 0) return 'zero';
  const ones = ['', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine',
    'ten', 'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen',
    'seventeen', 'eighteen', 'nineteen'];
  const tens = ['', '', 'twenty', 'thirty', 'forty', 'fifty', 'sixty', 'seventy', 'eighty', 'ninety'];

  function under1000(num: number): string {
    if (num < 20) return ones[num]!;
    if (num < 100) {
      const t = Math.floor(num / 10);
      const o = num % 10;
      return tens[t]! + (o ? '-' + ones[o] : '');
    }
    const h = Math.floor(num / 100);
    const r = num % 100;
    return ones[h]! + ' hundred' + (r ? ' ' + under1000(r) : '');
  }
  return under1000(n);
}

function ageSinceGenesis(now: number = Date.now()): { years: number; months: number } {
  const genesis = new Date(GENESIS_TS);
  const current = new Date(now);
  let years = current.getUTCFullYear() - genesis.getUTCFullYear();
  let months = current.getUTCMonth() - genesis.getUTCMonth();
  const days = current.getUTCDate() - genesis.getUTCDate();
  if (days < 0) months -= 1;
  if (months < 0) { years -= 1; months += 12; }
  return { years, months };
}

function nextHalvingDate(currentHeight: number): { month: string; year: number } {
  const nextHalvingHeight = Math.ceil((currentHeight + 1) / HALVING_INTERVAL) * HALVING_INTERVAL;
  const blocksRemaining = nextHalvingHeight - currentHeight;
  const msRemaining = blocksRemaining * 10 * 60 * 1000;
  const date = new Date(Date.now() + msRemaining);
  const month = date.toLocaleString('en-US', { month: 'short' });
  return { month, year: date.getFullYear() };
}

function halvingProgress(currentHeight: number): number {
  const epochStart = Math.floor(currentHeight / HALVING_INTERVAL) * HALVING_INTERVAL;
  return (currentHeight - epochStart) / HALVING_INTERVAL;
}

function blocksToHalving(currentHeight: number): number {
  const nextHalvingHeight = Math.ceil((currentHeight + 1) / HALVING_INTERVAL) * HALVING_INTERVAL;
  return nextHalvingHeight - currentHeight;
}

/** Approximate circulating supply based on block height */
function circulatingSupply(height: number): number {
  let supply = 0;
  let reward = 50;
  let h = 0;
  while (h < height) {
    const epochEnd = (Math.floor(h / HALVING_INTERVAL) + 1) * HALVING_INTERVAL;
    const end = Math.min(epochEnd, height);
    supply += (end - h) * reward;
    h = end;
    reward /= 2;
  }
  return supply;
}

function formatHash(h: number): string {
  if (h >= 1e18) return (h / 1e18).toFixed(1) + ' EH/s';
  if (h >= 1e15) return (h / 1e15).toFixed(1) + ' PH/s';
  if (h >= 1e12) return (h / 1e12).toFixed(1) + ' TH/s';
  return h.toFixed(0) + ' H/s';
}

export default function PulsePlus() {
  const [height, setHeight] = useState<number>(() => {
    try {
      const cached = localStorage.getItem('pulse_height');
      const parsed = cached ? parseInt(cached, 10) : NaN;
      return Number.isFinite(parsed) && parsed >= FALLBACK_BLOCK_HEIGHT ? parsed : FALLBACK_BLOCK_HEIGHT;
    } catch {
      return FALLBACK_BLOCK_HEIGHT;
    }
  });
  const [pulsed, setPulsed] = useState(false);
  const [now, setNow] = useState(Date.now());
  const [visible, setVisible] = useState(true);
  const [hashRate, setHashRate] = useState<number | null>(null);
  const [mempoolCount, setMempoolCount] = useState<number | null>(null);
  const [nodeCount, setNodeCount] = useState<number | null>(null);

  // Poll a first-party static snapshot generated by `npm run refresh-data`.
  useEffect(() => {
    let cancelled = false;
    let consecutiveFailures = 0;

    async function poll() {
      try {
        const res = await fetch('/pulse.json', { cache: 'no-store' });
        if (!res.ok) throw new Error('not ok');
        const data = await res.json() as PulseSnapshot;
        if (cancelled) return;
        const newHeight = Number(data.height);
        if (Number.isFinite(newHeight) && newHeight > 0) {
          consecutiveFailures = 0;
          setHeight((prev) => {
            if (newHeight > prev) {
              try { localStorage.setItem('pulse_height', String(newHeight)); } catch {}
              setPulsed(true);
              setTimeout(() => { if (!cancelled) setPulsed(false); }, 700);
              return newHeight;
            }
            return prev;
          });
        }
        if (Number.isFinite(data.hashRate)) setHashRate(data.hashRate ?? null);
        if (Number.isFinite(data.mempoolCount)) setMempoolCount(data.mempoolCount ?? null);
        if (Number.isFinite(data.nodeCount)) setNodeCount(data.nodeCount ?? null);
      } catch {
        consecutiveFailures += 1;
        if (consecutiveFailures >= 5 && !cancelled) setVisible(false);
      }
    }

    poll();
    const interval = setInterval(poll, 300000);
    return () => { cancelled = true; clearInterval(interval); };
  }, []);

  // Time tick
  useEffect(() => {
    const tick = setInterval(() => setNow(Date.now()), 60000);
    return () => clearInterval(tick);
  }, []);

  if (!visible) return null;

  const { years, months } = ageSinceGenesis(now);
  const halving = nextHalvingDate(height);
  const progress = halvingProgress(height);
  const remaining = blocksToHalving(height);
  const supply = circulatingSupply(height);
  const supplyPct = (supply / MAX_SUPPLY) * 100;

  const yearsWord = `${spellNumber(years)} year${years === 1 ? '' : 's'}`;
  const monthsWord = `${spellNumber(months)} month${months === 1 ? '' : 's'}`;

  return (
    <section class="pulse" aria-label="Bitcoin network clock">
      <div class="pulse-hd">
        <span class="pulse-lbl">Network Clock</span>
        <span class={`pulse-live ${pulsed ? 'pulse-live--flash' : ''}`} aria-hidden="true">
          <span class="pulse-live-dot" /> live
        </span>
      </div>

      <p class="pulse-line" aria-live="polite">
        Bitcoin is measured in blocks before it is measured in headlines. Block <span class={pulsed ? 'pulse-num pulse-num--flash' : 'pulse-num'}>{height.toLocaleString('en-US')}</span> &mdash; {yearsWord} and {monthsWord} since genesis.
      </p>

      <div class="pulse-track">
        <div
          class={`pulse-mark ${pulsed ? 'pulse-mark--step' : ''}`}
          style={{ left: `${(progress * 100).toFixed(3)}%` }}
          aria-hidden="true"
        />
      </div>
      <div class="pulse-ends">
        <span>Genesis &middot; Jan 2009</span>
        <span>{halving.month} {halving.year} &middot; Halving</span>
      </div>

      {/* ── Extended Protocol Stats ── */}
      <div class="pp-grid">
        <div class="pp-stat">
          <span class="pp-stat-lbl">Next Halving</span>
          <span class="pp-stat-val">{remaining.toLocaleString('en-US')} blocks</span>
          <span class="pp-stat-note">A predictable supply event built into the protocol</span>
        </div>

        {hashRate != null && (
          <div class="pp-stat">
            <span class="pp-stat-lbl">Hash Rate</span>
            <span class="pp-stat-val">{formatHash(hashRate)}</span>
            <span class="pp-stat-note">Energy protecting the network</span>
          </div>
        )}

        {mempoolCount != null && (
          <div class="pp-stat">
            <span class="pp-stat-lbl">Mempool</span>
            <span class="pp-stat-val">{mempoolCount.toLocaleString('en-US')} tx</span>
            <span class="pp-stat-note">Transactions waiting for inclusion</span>
          </div>
        )}

        {nodeCount != null && (
          <div class="pp-stat">
            <span class="pp-stat-lbl">Reachable Nodes</span>
            <span class="pp-stat-val">{nodeCount.toLocaleString('en-US')}</span>
            <span class="pp-stat-note">Independent verifiers</span>
          </div>
        )}
      </div>

      {/* ── Supply Progress ── */}
      <div class="pp-supply">
        <div class="pp-supply-hd">
          <span class="pp-supply-lbl">Supply Mined</span>
          <span class="pp-supply-pct">{supplyPct.toFixed(2)}%</span>
        </div>
        <div class="pp-supply-track">
          <div class="pp-supply-fill" style={{ width: `${supplyPct}%` }} />
        </div>
        <div class="pp-supply-ends">
          <span>0</span>
          <span>{(supply / 1_000_000).toFixed(2)}M / 21M</span>
        </div>
      </div>
    </section>
  );
}
