import { useEffect, useState } from 'preact/hooks';
import { FALLBACK_BLOCK_HEIGHT } from '@/lib/block-height';
import { spellNumber } from '@/lib/numbers';

const GENESIS_TS = 1231006505000;
const HALVING_INTERVAL = 210000;
const MAX_SUPPLY = 21_000_000;

interface PulseSnapshot {
  height?: number;
  hashRate?: number | null;
  mempoolCount?: number | null;
  fetchedAt?: string;
  source?: string;
}

interface Props {
  initialSnapshot?: PulseSnapshot;
}

function ageSinceGenesis(now: number = Date.now()): { years: number; months: number } {
  const genesis = new Date(GENESIS_TS);
  const current = new Date(now);
  let years = current.getUTCFullYear() - genesis.getUTCFullYear();
  let months = current.getUTCMonth() - genesis.getUTCMonth();
  const days = current.getUTCDate() - genesis.getUTCDate();
  if (days < 0) months -= 1;
  if (months < 0) { years -= 1; months += 12; }
  return { years, months };
}

function nextHalvingDate(currentHeight: number): { month: string; year: number } {
  const nextHalvingHeight = Math.ceil((currentHeight + 1) / HALVING_INTERVAL) * HALVING_INTERVAL;
  const blocksRemaining = nextHalvingHeight - currentHeight;
  const msRemaining = blocksRemaining * 10 * 60 * 1000;
  const date = new Date(Date.now() + msRemaining);
  const month = date.toLocaleString('en-US', { month: 'short' });
  return { month, year: date.getFullYear() };
}

function halvingProgress(currentHeight: number): number {
  const epochStart = Math.floor(currentHeight / HALVING_INTERVAL) * HALVING_INTERVAL;
  return (currentHeight - epochStart) / HALVING_INTERVAL;
}

function blocksToHalving(currentHeight: number): number {
  const nextHalvingHeight = Math.ceil((currentHeight + 1) / HALVING_INTERVAL) * HALVING_INTERVAL;
  return nextHalvingHeight - currentHeight;
}

/** Approximate circulating supply based on block height */
function circulatingSupply(height: number): number {
  let supply = 0;
  let reward = 50;
  let h = 0;
  while (h < height) {
    const epochEnd = (Math.floor(h / HALVING_INTERVAL) + 1) * HALVING_INTERVAL;
    const end = Math.min(epochEnd, height);
    supply += (end - h) * reward;
    h = end;
    reward /= 2;
  }
  return supply;
}

function formatHash(h: number): string {
  if (h >= 1e18) return (h / 1e18).toFixed(1) + ' EH/s';
  if (h >= 1e15) return (h / 1e15).toFixed(1) + ' PH/s';
  if (h >= 1e12) return (h / 1e12).toFixed(1) + ' TH/s';
  return h.toFixed(0) + ' H/s';
}

function formatSnapshotDate(value?: string): string {
  if (!value) return 'Network snapshot';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return 'Network snapshot';
  return `Snapshot · ${date.toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    timeZone: 'UTC',
  })} UTC`;
}

export default function PulsePlus({ initialSnapshot }: Props) {
  const [now, setNow] = useState(Date.now());

  // Everything except the clock is a build-time snapshot. The component used
  // to re-fetch /pulse.json every five minutes, but that file is generated by
  // `npm run refresh-data` and only changes on redeploy — the poll could never
  // return anything new, so it was ~288 requests a day per open tab for a
  // guaranteed identical body. Refresh the numbers by refreshing the data.
  const snapshotHeight = Number(initialSnapshot?.height);
  const height = Number.isFinite(snapshotHeight) && snapshotHeight > 0
    ? snapshotHeight
    : FALLBACK_BLOCK_HEIGHT;
  const hashRate = Number.isFinite(initialSnapshot?.hashRate) ? initialSnapshot?.hashRate ?? null : null;
  const mempoolCount = Number.isFinite(initialSnapshot?.mempoolCount) ? initialSnapshot?.mempoolCount ?? null : null;
  const snapshotDate = initialSnapshot?.fetchedAt;

  // Time tick
  useEffect(() => {
    const tick = setInterval(() => setNow(Date.now()), 60000);
    return () => clearInterval(tick);
  }, []);

  const { years, months } = ageSinceGenesis(now);
  const halving = nextHalvingDate(height);
  const progress = halvingProgress(height);
  const remaining = blocksToHalving(height);
  const supply = circulatingSupply(height);
  const supplyPct = (supply / MAX_SUPPLY) * 100;

  const yearsWord = `${spellNumber(years)} year${years === 1 ? '' : 's'}`;
  const monthsWord = `${spellNumber(months)} month${months === 1 ? '' : 's'}`;

  return (
    <section class="pulse" aria-label="Bitcoin network clock">
      <div class="pulse-hd">
        <span class="pulse-lbl">Network <em>Clock</em></span>
        <span class="pulse-live">
          <span class="pulse-live-dot" aria-hidden="true" /> {formatSnapshotDate(snapshotDate)}
        </span>
      </div>

      <p class="pulse-line" aria-live="polite">
        Bitcoin is measured in blocks before it is measured in headlines. Block <span class="pulse-num">{height.toLocaleString('en-US')}</span> &mdash; {yearsWord} and {monthsWord} since genesis.
      </p>

      <div class="pulse-track">
        <div
          class="pulse-mark"
          style={{ left: `${(progress * 100).toFixed(3)}%` }}
          aria-hidden="true"
        />
      </div>
      <div class="pulse-ends">
        <span>Genesis &middot; Jan 2009</span>
        <span>{halving.month} {halving.year} &middot; Halving</span>
      </div>

      {/* ── Extended Protocol Stats ── */}
      <div class="pp-grid">
        <div class="pp-stat">
          <span class="pp-stat-lbl">Next Halving</span>
          <span class="pp-stat-val">{remaining.toLocaleString('en-US')} blocks</span>
          <span class="pp-stat-note">A predictable supply event built into the protocol</span>
        </div>

        {hashRate != null && (
          <div class="pp-stat">
            <span class="pp-stat-lbl">Hash Rate</span>
            <span class="pp-stat-val">{formatHash(hashRate)}</span>
          <span class="pp-stat-note">Estimated computation committed to mining</span>
          </div>
        )}

        {mempoolCount != null && (
          <div class="pp-stat">
            <span class="pp-stat-lbl">Mempool</span>
            <span class="pp-stat-val">{mempoolCount.toLocaleString('en-US')} tx</span>
            <span class="pp-stat-note">Transactions waiting for inclusion</span>
          </div>
        )}

        <div class="pp-stat">
          <span class="pp-stat-lbl">Difficulty Epoch</span>
          <span class="pp-stat-val">{(height % 2016).toLocaleString('en-US')} / 2,016</span>
          <span class="pp-stat-note">Blocks into the current adjustment cycle</span>
        </div>
      </div>

      {/* ── Supply Progress ── */}
      <div class="pp-supply">
        <div class="pp-supply-hd">
          <span class="pp-supply-lbl">Supply Mined</span>
          <span class="pp-supply-pct">{supplyPct.toFixed(2)}%</span>
        </div>
        <div class="pp-supply-track">
          <div class="pp-supply-fill" style={{ width: `${supplyPct}%` }} />
        </div>
        <div class="pp-supply-ends">
          <span>0</span>
          <span>{(supply / 1_000_000).toFixed(2)}M / 21M</span>
        </div>
      </div>
    </section>
  );
}
